export const AFIP_INVOICE_TYPES = {
  FACTURA_A: '001',
  NOTA_DEBITO_A: '002',
  NOTA_CREDITO_A: '003',
  FACTURA_B: '006',
  NOTA_DEBITO_B: '007',
  NOTA_CREDITO_B: '008',
  FACTURA_C: '011',
  NOTA_DEBITO_C: '012',
  NOTA_CREDITO_C: '013',
  FACTURA_M: '051',
  NOTA_DEBITO_M: '052',
  NOTA_CREDITO_M: '053'
};

export const AFIP_DOCUMENT_TYPES = {
  CUIT: 80,
  CUIL: 86,
  CDI: 87,
  LE: 89,
  LC: 90,
  CI: 91,
  EN_TRAMITE: 92,
  ACTA_NACIMIENTO: 93,
  PASAPORTE: 94,
  CI_BS_AS: 95,
  DNI: 96,
  PASAPORTE_EX: 99,
  SIN_IDENTIFICAR: 99
};

export const AFIP_IVA_RATES = {
  NO_GRAVADO: 1,
  EXENTO: 2,
  CERO: 3,
  DIEZ_COMA_CINCO: 4, // 10.5%
  VEINTIUNO: 5,       // 21%
  VEINTISIETE: 6      // 27%
};

export const AFIP_CONCEPTS = {
  PRODUCTS: 1,
  SERVICES: 2,
  PRODUCTS_AND_SERVICES: 3
};

export const AFIP_CURRENCIES = {
  PESO_ARGENTINO: 'PES',
  DOLAR_ESTADOUNIDENSE: 'DOL'
};
